# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Honam's personal blog
tagline:             My blog
description:         Personal stuffs
url:                 http://walkingtospace.github.io/
baseurl:             ''
paginate:            5

